### ISSUE TITLE
Vimeo Depth Player

### ISSUE THREAD

**Issue by TheBiggestNumber** [vimeo/aframe-vimeo-component#12]
Hi. Fantastic component. Thanks! Are there any plans to add Vimeo Depth Player functionality?

**Comment by juniorxsound** [comment]
Thanks @TheBiggestNumber 🙌 It's not planned yet, but will make sure to update when it happens. It is however implemented with the [vimeo-threejs-player](https://github.com/vimeo/vimeo-threejs-player) on which this component is based on, the examples are live here:
https://vimeo-depth-player-playback.glitch.me/
https://vimeo-volumetric-video-livestreaming.glitch.me/

**Comment by juniorxsound** [comment]
Closing this for now, but will make sure to update once the Depth Player demos are ported to A-Frame component as well ⏰

**Comment by n5ro** [comment]
I'm going to need to use the Depth Player in A-Frame, and use the live streaming in A-Frame soonish. Can someone please help me port the vimeo depth player, and live stream player into Aframe? It's for a website that can potentially bring a lot of publicity to these Vimeo products.
