### ISSUE TITLE
Play video in aframe without a server

### ISSUE THREAD

**Issue by topherzee** [vimeo/aframe-vimeo-component#13]
Is it possible to include a vimeo video with purely client-side tech? As far as I can tell it is not, in which case please consider this a feature request.
As most of the Aframe examples and libraries work in a pure client-side context, I think it would be worth mentioning in the main readme that a server is required (if that's true), to avoid confusion.
(Great library and demo projects though - really happy vimeo is proactively supporting aframe!)

**Comment by juniorxsound** [comment]
Thanks @topherzee

Technically, it is possible. However, it means you are storing your API credentials (i.e token) in a publicly accessible way, which is **not** recommended for publicly available apps. If you are working locally and want to experiment with that, feel free to hack the plugin to fit your needs!

Thanks for the suggestion, we will update the README to reflect the need for a server 🙌

**Comment by topherzee** [comment]
Thanks for response and readme attention! I'll followup with another ticket about the token.
